export const ROLE = {
    ABOGADO: 'ABOGADO',
    JEFE_DE_SERVICIOS_JURIDICOS: 'JEFE DE SERVICIOS JURIDICOS',
    CLON_DE_JEFE_DE_SERVICIOS_JURI: 'CLONJEFESERV',
    CLON_ABOGADO: 'CLONABOGADO',
    JEFE_DE_DEPARTAMENTO: 'JEFE DE DEPARTAMENTO',
    CLON_JEFE_DE_DEPARTAMENTO: 'CLON DE JEFE DE DEPARTAMENTO',
    COORDINADOR: 'COORDINADOR',
    CLON_DE_COORDINADOR: 'CLONCOORD',
    JEFE_OFICINA:'JEFE DE OFICINA',
    JEFE_DIVISION: 'JEFE DE DIVISION',
    JEFE_DE_AREA: 'JEFE AREA',
    ADMINISTRADOR: 'ADMINISTRADOR',
    CLON_JEFE_AREA:'CLONJEFEAREA',
    SUBJEFE_DE_DIVISIÓN: 'SUB-JEFE DE DIVISION',
    CONSULTA: 'CONSULTA',
    LECTURA:'SOLO_LECTURA',
    CAPTURA: 'CAPTURA-NC'
};

