spring:
  jackson:
    date-format: yyyy-MM-dd
    time-zone: America/Mexico_City
    locale: es_MX    
    serialization:
      fail-on-empty-beans: false
  profiles: default
  datasource:
    #url: ${CADENA_CONEXION_DB_MJLSSC}
    #username: ${USER_DB_MJLSSC}
    #password: ${PASSWORD_DB_MJLSSC}
    #url:  jdbc:mariadb:failover://localhost:3306/jlisscbdqa01?autoReconnect=true
    url:  jdbc:mariadb://10.100.8.166:3306/NMLSSCBDQA01?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    username: NMLSSCBD_USER
    password: NML55CBD_U534
    
    driverClassName: org.mariadb.jdbc.Driver
  jpa:
    properties:
      hibernate:
        jdbc:
          time_zone: America/Mexico_City
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    database-platform: org.hibernate.dialect.MariaDB103Dialect
  
server:
  servlet:
    contextPath: /msmjlssc-catalogos/v1
  port: 8080
  
authorization:
  #signingKey: ${SIGNING_KEY_OAUTH}
  signingKey: algun_codigo_secreto_qwerty_pa_validar_token

info:
  component: Microservicio Para Funcionalidad Catalogos Modulo Juicio Laboral MJL

logging:
  file:
    name: msmjlssc-catalogos.log
  pattern:
    console: "%d %-5level %logger : %msg%n"
    file: "%d %-5level [%thread] %logger : %msg%n"
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    org.springframework: INFO
    #mx.gob.imss.cit.mjlssc: ${MJLSSC_LOG_LEVEL}
    mx.gob.imss.cit.mjlssc: DEBUG
    
management:
  endpoints:
    web:
      base-path: /msbase-manager/actuator
      exposure:
        include: health, info, env, beans, metrics, threaddump, vigencia, genericEndPoints
  endpoint:
    health:
      show-details: always
    security:
      enabled: false
  health:
    defaults:
      enabled: false
    db:
      enabled: true
    ping:
      enabled: true
  info:
    git:
      mode: full
#nml:
 # schema: ${MJLSSC_NML_SCHEMA}
---
spring:
  jackson:
    date-format: yyyy-MM-dd
    time-zone: America/Mexico_City
    locale: es_MX    
    serialization:
      fail-on-empty-beans: false
  profiles: local
  datasource:
    url: jdbc:mariadb://10.100.8.166:3306/MAISSCBDQA01?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    username: MAISSCBD_USER
    password: M55ACBDI_U534
    driverClassName: org.mariadb.jdbc.Driver
  jpa:
    properties:
      hibernate:
        jdbc:
          time_zone: America/Mexico_City
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    database-platform: org.hibernate.dialect.MariaDB103Dialect
  
server:
  servlet:
    contextPath: /msmjlssc-catalogos/v1
  port: 9092

info:
  component: Microservicio de catalogos para la funcionalidad del modulo juicio laboral
  
authorization:
  signingKey: algun_codigo_secreto_qwerty_pa_validar_token

logging:
  file:
    name: msmjlssc-catalogos.log
  pattern:
    console: "%d %-5level %logger : %msg%n"
    file: "%d %-5level [%thread] %logger : %msg%n"
  level:
    org.springframework: INFO
    mx.gob.imss.cit.mjlssc: INFO
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE

management:
  endpoints:
    web:
      base-path: /msbase-manager/actuator
      exposure:
        include: health, info, env, beans, metrics, threaddump, vigencia, genericEndPoints
  endpoint:
    health:
      show-details: always
    security:
      enabled: false
  health:
    defaults:
      enabled: false
    db:
      enabled: true
    ping:
      enabled: true
  info:
    git:
      mode: full
nml:
  schema: NMLSSCBDQA01